=== aakasmikgh/Web-Technology/lab5/Task 02/students.dtd
<!ELEMENT students (student+)>
<!ELEMENT student (name, id, subject, grade)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT subject (#PCDATA)>
<!ELEMENT grade (#PCDATA)>

=== aakasmikgh/Web-Technology/lab5/Task 02/students.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE students SYSTEM "students.dtd">
<students>
    <student>
        <name>Aakasmik</name>
        <id>001</id>
        <subject>Mathematics</subject>
        <grade>A</grade>
    </student>
    <student>
        <name>Abhigyan</name>
        <id>003</id>
        <subject>Science</subject>
        <grade>A+</grade>
    </student>
    <student>
        <name>Aavash</name>
        <id>014</id>
        <subject>History</subject>
        <grade>B+</grade>
    </student>
</students>
